# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$PYVER
after_success:
- codecov


